name: Build and Run iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: [macos-latest]
    env:
      XC_VERSION: '12.4'
      XC_PROJECT: 'debugger_challenge.xcodeproj'
      XC_SCHEME: 'debugger_challenge'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: actions/setup-xcode@v2
      with:
        xcode-version: ${{ env.XC_VERSION }}

    - name: Build and run on physical device
      run: |
        xcodebuild -project "$XC_PROJECT" -scheme "$XC_SCHEME" -destination 'generic/platform=iOS' build
