name: Build iOS App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macos-latest

    env:
      XC_PROJECT: 'debugger_challenge.xcodeproj'
      XC_SCHEME: 'debugger_challenge'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Xcode
      run: sudo xcode-select --install || true

    - name: Select Xcode version
      run: sudo xcode-select -s /Applications/Xcode.app


    - name: Build iOS app
      run: xcodebuild -project "${{ env.XC_PROJECT }}" -scheme "${{ env.XC_SCHEME }}" -destination 'generic/platform=iOS' -arch x86_64 -arch arm64 build
